[project]
name = "splitpay"
description = "Automated payment splitting"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.splitpay]
path = "contracts/splitpay.clar"

[repl.analysis]
passes = ["check_checker"]
